on:
  pull_request:
    branches:
      - 'master'


jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Log
        run: |
          printf "branch: %s\n" "${{ github.GITHUB_REF_NAME }}"
          printf "branch: %s\n" "${{ github.ref }}"
          printf "branch: %s\n" "${{ github.ref_name }}"
          printf "branch: %s\n" "$GITHUB_REF_NAME"
          
