on:
  release:
    types:
      - published

jobs:
  set_version:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set version env
        # writes APP_VERSION to GITHUB_ENV
        run: ./.github/scripts/set-version.sh
        env:
          GITHUB_REF_TYPE: ${{ env.GITHUB_REF_TYPE }}
          GITHUB_REF_NAME: ${{ github.GITHUB_REF_NAME }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_ENV: ${{ env.GITHUB_ENV }}

      - name: check
        run: |
          echo "APP_VERSION: ${{env.APP_VERSION}}"
